import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  typescriptSidebar: [{type: 'autogenerated', dirName: 'TypeScript'}],
  javaSidebar: [{type:'autogenerated', dirName: 'Java'}]
};

export default sidebars;
